---
title: "Zinc"
author: "Valerie Ingalls"
date: "2022-10-28"
output: html_document
---

```{r setup, include=FALSE}
library(foreign)
library(survey)
library(dplyr)
library(stringr)
library(tidyr)
library(bestNormalize)
library(ggplot2)
```


```{r import}
demo11 <- read.xport("../Data/RAW_data/DEMO_G.XPT")
auq11 <- read.xport("../Data/RAW_data/AUQ_G.XPT")
zinc11 <- read.xport("../Data/RAW_data/CUSEZN_G.XPT")
aux11 <- read.xport("../Data/RAW_data/AUX_G.XPT")
fast11 <- read.xport("../Data/RAW_data/FASTQX_G.XPT")

demo15 <- read.xport("../Data/RAW_data/DEMO_I.XPT")
auq15 <- read.xport("../Data/RAW_data/AUQ_I.XPT")
zinc15 <- read.xport("../Data/RAW_data/CUSEZN_I.XPT")
aux15 <- read.xport("../Data/RAW_data/AUX_I.XPT")
fast15 <- read.xport("../Data/RAW_data/FASTQX_I.XPT")
```


```{r join}
zinc_data15 <- full_join(demo15, auq15) %>%
  full_join(zinc15) %>%
  full_join(aux15) %>%
  full_join(fast15)

zinc_data11 <- full_join(demo11, auq11) %>%
  full_join(zinc11) %>%
  full_join(aux11) %>%
  full_join(fast11)

zinc_all <- full_join(zinc_data11, zinc_data15)
```


```{r cleaning}
zinc_trimmed <- zinc_all %>%
  select(c(SEQN, SDDSRVYR, RIAGENDR, RIDAGEYR, RIDRETH3, WTINT2YR, WTMEC2YR, SDMVPSU, SDMVSTRA, AUQ191, AUQ100, AUXU500R, AUXU1K1R, AUXU2KR, AUXU500L, AUXU1K1L, AUXU2KL, AUXU3KR, AUXU4KR, AUXU6KR, AUXU8KR, AUXU3KL, AUXU4KL, AUXU6KL, AUXU8KL, AUQ330, AUQ331, AUQ370, AUQ300, WTSA2YR, LBXSCU, LBXSSE, LBXSZN, LBDSCUSI, LBDSSESI, LBDSZNSI, PHDSESN))

zinc_refactor <- zinc_trimmed %>%
  rename("cycle" = "SDDSRVYR",
         "sex" = "RIAGENDR",
         "age_yrs" = "RIDAGEYR",
         "ethnicity" = "RIDRETH3",
         "interview_weight" = "WTINT2YR",
         "examination_weight" = "WTMEC2YR",
         "subsample_weight" = "WTSA2YR",
         "psu" = "SDMVPSU",
         "stratum" = "SDMVSTRA",
         "tinnitus_any" = AUQ191,
         "speech_in_noise" = AUQ100,
         "non_work_noise" = AUQ370,
         "firearms" = AUQ300,
         "copper_umol/L" = LBDSCUSI,
         "selenium_umol/L" = LBDSSESI,
         "zinc_umol/L" = LBDSZNSI,
         "copper_ug/dL" = LBXSCU,
         "selenium_ug/dL" = LBXSSE,
         "zinc_ug/dL" = LBXSZN,
         "session" = PHDSESN
  ) %>%
  mutate(
         "work_noise" = if_else(!is.na(AUQ330), AUQ330, AUQ331),
         "ethnicity" = if_else(`ethnicity` == 3, 1, 2), # 1 = white, 2 is non white/Hispanic
         "age_group" = if_else(age_yrs < 30, 1, 
                               if_else(age_yrs < 40, 2, 
                                       if_else(age_yrs < 50, 3, 
                                               if_else(age_yrs < 60, 4, 5)))),
         across(c(AUXU500R, AUXU1K1R, AUXU2KR, AUXU3KR, AUXU4KR, AUXU6KR, AUXU8KR, AUXU500L,
                   AUXU1K1L, AUXU2KL, AUXU3KL, AUXU4KL, AUXU6KL, AUXU8KL), ~na_if(., 888)),
         across(c(AUXU500R, AUXU1K1R, AUXU2KR, AUXU3KR, AUXU4KR, AUXU6KR, AUXU8KR, AUXU500L,
                   AUXU1K1L, AUXU2KL, AUXU3KL, AUXU4KL, AUXU6KL, AUXU8KL), ~if_else(. == 666, 110, .)),
         "mid_pta_right" = (AUXU500R + AUXU1K1R + AUXU2KR) / 3,
         "mid_pta_left" = (AUXU500L + AUXU1K1L + AUXU2KL) / 3,
         "high_pta_right" = (AUXU3KR + AUXU4KR + AUXU6KR + AUXU8KR) / 4,
         "high_pta_left" = (AUXU3KL + AUXU4KL + AUXU6KL + AUXU8KL) / 4,
         "combined_subsample_weight" = subsample_weight/2,
         across(c(tinnitus_any, sex, non_work_noise, firearms, work_noise, speech_in_noise),  ~na_if(., 7)),
         across(c(tinnitus_any, sex, non_work_noise, firearms, work_noise, speech_in_noise),  ~na_if(., 9)),
         "cycle" = if_else(cycle == 7, "2011", "2015"),
         "zinc_cutoff" = if_else(age_yrs >= 10, 
                                     if_else(sex == 1, if_else(session == 1, 74, 61), 
                                     if_else(session == 1, 70, 59)),
                                     if_else(session == 1, 65, 57)),
         "zinc_deficiency" = if_else(`zinc_ug/dL` < zinc_cutoff, 1, 0), # 0 is no deficiency
         "copper_deficiency" = if_else(`copper_ug/dL` < 63.7, 1, 0),
         "selenium_deficiency" = if_else(`selenium_ug/dL` < 85, 1, 0),
         "tinnitus_any" = if_else(tinnitus_any == 1, 1, 0),
         "age_sq" = age_yrs^2
  ) %>%
  select(-c(AUXU500R, AUXU1K1R, AUXU2KR, AUXU500L, AUXU1K1L, AUXU2KL, AUXU3KR, AUXU4KR, AUXU6KR, AUXU8KR, AUXU3KL, AUXU4KL, AUXU6KL, AUXU8KL, AUQ330, AUQ331, -subsample_weight, zinc_cutoff, session))
    
```


```{r subset}
zinc_SPSS <- zinc_refactor %>%
    replace(is.na(.), "")

zinc_subset <- zinc_refactor %>%
  filter(!is.na(`zinc_ug/dL`)) %>%
  filter(!is.na(`selenium_ug/dL`)) %>%
  filter(!is.na(`copper_ug/dL`)) %>%
  filter(!is.na(tinnitus_any)) %>%
  filter(!is.na(speech_in_noise))

```

```{r designs}
cutoff_design <- svydesign(data = zinc_subset, id = ~psu, strata = ~stratum, weights = ~combined_subsample_weight, nest = TRUE)

tinnitus_design <- svydesign(data = zinc_subset, id = ~psu, strata = ~stratum, weights = ~combined_subsample_weight, nest = TRUE)
```

```{r chisq}
sextest <- chisq.test(zinc_subset$sex, zinc_subset$tinnitus_any)
sextest$observed
sextest

agetest <- chisq.test(zinc_subset$age_group, zinc_subset$tinnitus_any)
agetest$observed
agetest

ethtest <- chisq.test(zinc_subset$ethnicity, zinc_subset$tinnitus_any)
ethtest$observed
ethtest
```


```{r regression}
svyttest(zinc_deficiency~tinnitus_any, design = tinnitus_design)

#tinnitus_design %>%
#  subset(tinnitus_any == 1) %>%
#  svymean(~`zinc_ug/dL`, .)
#tinnitus_design %>%
#  subset(tinnitus_any != 1) %>%
#  svymean(~`zinc_ug/dL`, .)
#tinnitus_design %>%
#  subset(tinnitus_any == 1) %>%
#  svymean(~zinc_deficiency, .)
#tinnitus_design %>%
#  subset(tinnitus_any != 1) %>%
#  svymean(~zinc_deficiency, .)


logit1 <- svyglm(formula = zinc_deficiency ~ tinnitus_any + sex + ethnicity + speech_in_noise + non_work_noise + firearms + work_noise + age_group, family = quasibinomial, design = tinnitus_design, na.action = na.omit)

logit2 <- svyglm(formula = zinc_deficiency ~ tinnitus_any + sex + ethnicity + age_group + speech_in_noise, family = quasibinomial, design = tinnitus_design, na.action = na.omit)

summary(logit1, correlation = TRUE)
anova(logit1)

summary(logit2, correlation = TRUE)

exp(cbind(OR = coef(logit2), confint.default(logit2)))

logit3 <- svyglm(formula = copper_deficiency ~ tinnitus_any + sex + ethnicity + age_group + speech_in_noise, family = quasibinomial, design = tinnitus_design, na.action = na.omit)

summary(logit3)
exp(cbind(OR = coef(logit3), confint.default(logit3)))

logit4 <- svyglm(formula = selenium_deficiency ~ tinnitus_any + sex + ethnicity + age_group + speech_in_noise, family = quasibinomial, design = tinnitus_design, na.action = na.omit)

summary(logit4)
exp(cbind(OR = coef(logit4), confint.default(logit4)))


#svyttest(`zinc_ug/dL`~tinnitus_any, design = tinnitus_design, alternative = "two.sided", paired = TRUE, conf.level = .95)

multilin2 <- svyglm(formula = `zinc_ug/dL` ~ tinnitus_any + sex + ethnicity + age_group + speech_in_noise, design = tinnitus_design, na.action = na.omit)

summary(multilin2, correlation = TRUE)

multilin3 <- svyglm(formula = `copper_ug/dL` ~ tinnitus_any + sex + ethnicity + age_group + speech_in_noise, design = tinnitus_design, na.action = na.omit)

summary(multilin3)

multilin4 <- svyglm(formula = `selenium_ug/dL` ~ tinnitus_any + sex + ethnicity + age_group + speech_in_noise, design = tinnitus_design, na.action = na.omit)

summary(multilin4)



```


```{r histograms}
subset(tinnitus_design, tinnitus_any == 0) %>%
  svyhist(formula = ~`zinc_ug/dL`, design = ., breaks = 300)

subset(tinnitus_design, tinnitus_any == 1) %>%
  svyhist(formula = ~`zinc_ug/dL`, design = ., breaks = 300)
```


```{r mean-comparison}
subset(tinnitus_design, tinnitus_any == 0) %>%
  svymean(~zinc_deficiency, .)

subset(tinnitus_design, tinnitus_any == 1) %>%
  svymean(~zinc_deficiency, .)

subset(tinnitus_design, tinnitus_any == 0) %>%
  svymean(~copper_deficiency, .)

subset(tinnitus_design, tinnitus_any == 1) %>%
  svymean(~copper_deficiency, .)

subset(tinnitus_design, tinnitus_any == 0) %>%
  svymean(~selenium_deficiency, .)

subset(tinnitus_design, tinnitus_any == 1) %>%
  svymean(~selenium_deficiency, .)
```


```{r}
deficient_tbl <- tibble("tinnitus" = c(9.807, 0.621, 0.145), "no tinnitus" = c(15.664, 0.604, 0.374))

ggplot(data = deficient_tbl, mapping = aes(x =  ))
```



```{r}
zincresid <- rstandard(multilin2)
shapiro.test(zincresid)

hist(zincresid, breaks = 100)
hist(zinc_norm$chosen_transform$x.t, breaks = 100)

zinc_norm <-bestNormalize(zinc_refactor$`zinc_ug/dL`)

zinc_chosen <- zinc_norm$chosen_transform$x.t

zinc_norm_df <- zinc_refactor %>%
  mutate(
    "zinc_norm" = `zinc_chosen`
  )

zinc_norm_subset_df <- zinc_norm_df %>%
  filter(!is.na(zinc_norm))



copper_norm <-bestNormalize(zinc_refactor$`copper_ug/dL`)

copper_chosen <- copper_norm$chosen_transform$x.t

copper_norm_df <- zinc_refactor %>%
  mutate(
    "copper_norm" = `copper_chosen`
  )

copper_norm_subset_df <- copper_norm_df %>%
  filter(!is.na(copper_norm))

selenium_norm <-bestNormalize(zinc_refactor$`selenium_ug/dL`)

selenium_chosen <- selenium_norm$chosen_transform$x.t

selenium_norm_df <- zinc_refactor %>%
  mutate(
    "selenium_norm" = `selenium_chosen`
  )

selenium_norm_subset_df <- selenium_norm_df %>%
  filter(!is.na(selenium_norm))

norm_data <- full_join(selenium_norm_subset_df, copper_norm_subset_df) %>%
  full_join(zinc_norm_subset_df)


normed_design <- svydesign(data = norm_data, id = ~psu, strata = ~stratum, weights = ~combined_subsample_weight, nest = TRUE) %>%
  subset(!is.na(tinnitus_any))


normed_lin_zinc <- svyglm(formula = zinc_norm ~ tinnitus_any + sex + ethnicity + age_yrs, design = normed_design, na.action = na.omit)

normed_lin_cu <- svyglm(formula = copper_norm ~ tinnitus_any + sex + ethnicity + age_yrs, design = normed_design, na.action = na.omit)

normed_lin_se <- svyglm(formula = selenium_norm ~ tinnitus_any + sex + ethnicity + age_yrs, design = normed_design, na.action = na.omit)

summary(normed_lin_zinc)
summary(normed_lin_cu)
summary(normed_lin_se)

norm_zinc_resid <- rstandard(normed_lin_zinc)
shapiro.test(norm_zinc_resid)
hist(norm_zinc_resid, breaks = 100)


cu_no_outlier <-  normed_design%>%
  subset(copper_norm > -15)

cu_lin_no_outlier <- svyglm(formula = copper_norm ~ tinnitus_any + sex + ethnicity + age_yrs, design = cu_no_outlier, na.action = na.omit)
  
norm_cu_resid <- rstandard(cu_lin_no_outlier)
shapiro.test(norm_cu_resid)
hist(norm_cu_resid, breaks = 100)

norm_se_resid <- rstandard(normed_lin_se)
shapiro.test(norm_se_resid)
hist(norm_se_resid, breaks = 100)
```





```{r}
svyhist(~`zinc_ug/dL`, design = tinnitus_design, breaks = 50)
```



dummy variables regression
remove profound










