---
title: "Zinc"
author: "Valerie Ingalls"
date: "2022-10-28"
output: html_document
---

```{r setup, include=FALSE}
library(foreign)
library(survey)
library(dplyr)
library(stringr)
library(tidyr)
library(bestNormalize)
library(ggplot2)
```


```{r import}
demo11 <- read.xport("../Data/RAW_data/DEMO_G.XPT")
auq11 <- read.xport("../Data/RAW_data/AUQ_G.XPT")
zinc11 <- read.xport("../Data/RAW_data/CUSEZN_G.XPT")
aux11 <- read.xport("../Data/RAW_data/AUX_G.XPT")
fast11 <- read.xport("../Data/RAW_data/FASTQX_G.XPT")

demo15 <- read.xport("../Data/RAW_data/DEMO_I.XPT")
auq15 <- read.xport("../Data/RAW_data/AUQ_I.XPT")
zinc15 <- read.xport("../Data/RAW_data/CUSEZN_I.XPT")
aux15 <- read.xport("../Data/RAW_data/AUX_I.XPT")
fast15 <- read.xport("../Data/RAW_data/FASTQX_I.XPT")
```


```{r join}
zinc_data15 <- full_join(demo15, auq15) %>%
  full_join(zinc15) %>%
  full_join(aux15) %>%
  full_join(fast15)

zinc_data11 <- full_join(demo11, auq11) %>%
  full_join(zinc11) %>%
  full_join(aux11) %>%
  full_join(fast11)

zinc_all <- full_join(zinc_data11, zinc_data15)
```


```{r cleaning}
zinc_trimmed <- zinc_all %>%
  select(c(SEQN, SDDSRVYR, RIAGENDR, RIDAGEYR, RIDRETH3, WTINT2YR, WTMEC2YR, SDMVPSU, SDMVSTRA, AUQ191, AUQ280, AUQ250, AUQ260, AUQ100, AUXU500R, AUXU1K1R, AUXU2KR, AUXU500L, AUXU1K1L, AUXU2KL, AUXU3KR, AUXU4KR, AUXU6KR, AUXU8KR, AUXU3KL, AUXU4KL, AUXU6KL, AUXU8KL, AUQ330, AUQ331, AUQ370, AUQ300, WTSA2YR, LBXSCU, LBXSZN, PHDSESN))

zinc_refactor <- zinc_trimmed %>%
  rename("cycle" = "SDDSRVYR",
         "sex" = "RIAGENDR",
         "age_yrs" = "RIDAGEYR",
         "ethnicity" = "RIDRETH3",
         "interview_weight" = "WTINT2YR",
         "examination_weight" = "WTMEC2YR",
         "subsample_weight" = "WTSA2YR",
         "psu" = "SDMVPSU",
         "stratum" = "SDMVSTRA",
         "tinnitus_any" = AUQ191,
         "tinnitus_severity" = AUQ280,
         "tinnitus_duration" = AUQ250,
         "noise_only" = AUQ260,
         "speech_in_noise" = AUQ100,
         "non_work_noise" = AUQ370,
         "firearms" = AUQ300,
         "copper_ug/dL" = LBXSCU,
         "zinc_ug/dL" = LBXSZN,
         "session" = PHDSESN
  ) %>%
  mutate(
         "work_noise" = if_else(!is.na(AUQ330), AUQ330, AUQ331),
         "ethnicity" = if_else(`ethnicity` == 3, 1, 2), # 1 = white, 2 is non white/Hispanic
         "age_group" = if_else(age_yrs < 30, 1, 
                               if_else(age_yrs < 40, 2, 
                                       if_else(age_yrs < 50, 3, 
                                               if_else(age_yrs < 60, 4, 5)))),
         across(c(AUXU500R, AUXU1K1R, AUXU2KR, AUXU3KR, AUXU4KR, AUXU6KR, AUXU8KR, AUXU500L,
                   AUXU1K1L, AUXU2KL, AUXU3KL, AUXU4KL, AUXU6KL, AUXU8KL), ~na_if(., 888)),
         across(c(AUXU500R, AUXU1K1R, AUXU2KR, AUXU3KR, AUXU4KR, AUXU6KR, AUXU8KR, AUXU500L,
                   AUXU1K1L, AUXU2KL, AUXU3KL, AUXU4KL, AUXU6KL, AUXU8KL), ~if_else(. == 666, 110, .)),
         "mid_pta_right" = (AUXU500R + AUXU1K1R + AUXU2KR) / 3,
         "mid_pta_left" = (AUXU500L + AUXU1K1L + AUXU2KL) / 3,
         "high_pta_right" = (AUXU3KR + AUXU4KR + AUXU6KR + AUXU8KR) / 4,
         "high_pta_left" = (AUXU3KL + AUXU4KL + AUXU6KL + AUXU8KL) / 4,
         "combined_subsample_weight" = subsample_weight/2,
         across(c(tinnitus_any, tinnitus_severity, tinnitus_duration, noise_only, sex, non_work_noise, firearms, work_noise, speech_in_noise),  ~na_if(., 7)),
         across(c(tinnitus_any, tinnitus_severity, tinnitus_duration, noise_only, sex, non_work_noise, firearms, work_noise, speech_in_noise),  ~na_if(., 9)),
         "problematic" = if_else(tinnitus_severity == 1, 0, 1),
         "acute_chronic" = if_else(tinnitus_duration >= 3, 1, 0),
         "tinnitus_type" = 
         "cycle" = if_else(cycle == 7, "2011", "2015"),
         "zinc_cutoff" = if_else(age_yrs >= 10, 
                                     if_else(sex == 1, if_else(session == 1, 74, 61), 
                                     if_else(session == 1, 70, 59)),
                                     if_else(session == 1, 65, 57)),
         "zinc_deficiency" = if_else(`zinc_ug/dL` < zinc_cutoff, 1, 0), # 0 is no deficiency
         "copper_deficiency" = if_else(`copper_ug/dL` < 63.7, 1, 0),
         "tinnitus_any" = if_else(tinnitus_any == 1, 1, 0)
  ) %>%
  select(-c(AUXU500R, AUXU1K1R, AUXU2KR, AUXU500L, AUXU1K1L, AUXU2KL, AUXU3KR, AUXU4KR, AUXU6KR, AUXU8KR, AUXU3KL, AUXU4KL, AUXU6KL, AUXU8KL, AUQ330, AUQ331, subsample_weight, zinc_cutoff, session))
    
```


```{r subset}
# file without NA's for easier use with SPSS; no purpose here
zinc_SPSS <- zinc_refactor %>%
    replace(is.na(.), "")


# removing rows with incomplete data; partially for cleanliness, partially for better functioning with later analyses
zinc_subset <- zinc_refactor %>%
  filter(!is.na(`zinc_ug/dL`)) %>%
  filter(!is.na(`copper_ug/dL`)) %>%
  filter(!is.na(tinnitus_any)) %>%
  filter(!is.na(speech_in_noise))
```

```{r write}
write.csv(zinc_subset, file = "../Data/processed_metal_data.csv")
```

